'use client';
import { useEffect, useMemo, useState } from 'react';
import { Bell, CheckCircle2, MapPin, Truck, UserCircle, Wallet, XCircle } from 'lucide-react';
import LanguageSelector from './LanguageSelector';
import LocationButton from './LocationButton';
import { apiGet, apiPatch, apiPost } from '../lib/api';
import './Logistics.css';

type Profile={logisticsId:string;capacityKg:number;capabilities:string[];vehicleType?:string;locationText:string;latitude:number;longitude:number};
type Offer={id:string;status:string;distanceKm:number;etaMinutes:number;fee:number;order:{code:string;buyer:{firstName:string;lastName:string};farmer:{firstName:string;lastName:string};items:{quantity:number;unit:string;product:{name:string}}[];shipment?:{status:string}}};
export default function Logistics(){
 const [profile,setProfile]=useState<Profile|null>(null),[offers,setOffers]=useState<Offer[]>([]),[capacity,setCapacity]=useState(''),[vehicle,setVehicle]=useState(''),[capabilities,setCapabilities]=useState(''),[location,setLocation]=useState({text:'',latitude:0,longitude:0}),[message,setMessage]=useState(''),[tab,setTab]=useState<'offers'|'profile'>('offers');
 useEffect(()=>{document.title='KhetLink | Logistics Interface';(async()=>{try{const m=await apiGet<any>('/me');if(m.logistics)setProfile(m.logistics);const o=await apiGet<Offer[]>('/logistics/offers');setOffers(o);}catch{}})()},[]);
 const refresh=async()=>{try{setOffers(await apiGet<Offer[]>('/logistics/offers'));}catch{}};
 const save=async()=>{try{const m=await apiPost<any>('/profile',{role:'LOGISTICS',capacityKg:Number(capacity),capabilities:capabilities.split(',').map(x=>x.trim()).filter(Boolean),vehicleType:vehicle,locationText:location.text,latitude:location.latitude,longitude:location.longitude});setProfile(m.profile);setMessage('Profile saved.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save profile.')}};
 const accept=async(id:string)=>{try{await apiPatch(`/logistics-offers/${id}`,{status:'ACCEPTED'});setMessage('Offer accepted.');refresh();}catch(e){setMessage(e instanceof Error?e.message:'Unable to accept offer.')}};
 const decline=async(id:string)=>{try{await apiPatch(`/logistics-offers/${id}`,{status:'REJECTED'});refresh();}catch{}};
 const paidOffers=useMemo(()=>offers.filter(o=>o.status==='PENDING'||o.status==='ACCEPTED'),[offers]);
 return <div className="logistics-root"><header className="logistics-header"><div className="logistics-brand"><img src="/Khetlink_Logo.svg" alt="KhetLink"/><div><strong>KhetLink</strong><span>Transport & delivery</span></div></div><nav><button className={tab==='offers'?'active':''} onClick={()=>setTab('offers')}>Transport Offers</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>Profile</button></nav><div className="logistics-actions"><LanguageSelector compact/><Bell size={19}/><UserCircle size={28}/></div></header>
 {message&&<div className="logistics-message">{message}</div>}
 {!profile||tab==='profile'?<main className="logistics-profile"><section><p className="eyebrow">LOGISTICS PROFILE</p><h1>Set up your transport profile</h1><p>Capacity and capabilities are mandatory before paid delivery offers can be accepted.</p><div className="logistics-form"><label>Capacity (kg)<input value={capacity || profile?.capacityKg || ''} onChange={e=>setCapacity(e.target.value)} type="number" min="1"/></label><label>Vehicle type<input value={vehicle || profile?.vehicleType || ''} onChange={e=>setVehicle(e.target.value)} placeholder="Truck, mini truck, van…"/></label><label>Capabilities<input value={capabilities || profile?.capabilities?.join(', ') || ''} onChange={e=>setCapabilities(e.target.value)} placeholder="Cold chain, fragile, bulk…"/></label><label>Location<div className="location-input"><input value={location.text || profile?.locationText || ''} onChange={e=>setLocation({...location,text:e.target.value})} placeholder="City, state, location details"/><LocationButton onLocation={x=>setLocation(x)}/></div></label><button className="primary" onClick={save}>Save profile</button></div></section></main>:<main className="logistics-main"><section className="logistics-hero"><div><p className="eyebrow">TRANSPORT OFFERS</p><h1>Paid orders ready for delivery</h1><p>Offers are sent to nearby providers first and only paid Buyer–Farmer orders appear here.</p></div><div className="capacity-card"><Truck size={25}/><strong>{profile.capacityKg.toLocaleString()} kg</strong><span>Capacity</span></div></section><section className="offer-grid">{paidOffers.length===0?<div className="empty">No paid delivery offers right now.</div>:paidOffers.map(o=><article className="offer-card" key={o.id}><div className="offer-top"><span>{o.order.code}</span><b className={o.status==='ACCEPTED'?'accepted':''}>{o.status}</b></div><h3>{o.order.items.map(i=>`${i.product.name} · ${i.quantity} ${i.unit}`).join(', ')}</h3><p><MapPin size={15}/> {o.distanceKm.toFixed(1)} km · {o.etaMinutes} min</p><p><UserCircle size={15}/> {o.order.farmer.firstName} {o.order.farmer.lastName} → {o.order.buyer.firstName} {o.order.buyer.lastName}</p><div className="offer-fee"><Wallet size={17}/><strong>₹{o.fee.toFixed(2)}</strong><span>delivery fee</span></div>{o.status==='PENDING'&&<div className="offer-buttons"><button className="primary" onClick={()=>accept(o.id)}><CheckCircle2 size={16}/> Accept</button><button className="secondary" onClick={()=>decline(o.id)}><XCircle size={16}/> Decline</button></div>}</article>)}</section></main>}
 </div>
}
