import "dotenv/config";
import express from "express";
import cookieParser from "cookie-parser";
import cors from "cors";
import authRoutes from "./auth.routes.js";
import apiRoutes from "./api.routes.js";
import { startJobs } from "./jobs.js";

const app = express();
const PORT = Number(process.env.PORT ?? 4000);
const FRONTEND_ORIGIN = process.env.FRONTEND_ORIGIN ?? "http://localhost:3000";
app.use(cors({ origin: FRONTEND_ORIGIN, credentials: true }));
app.use(express.json({ limit: "5mb" }));
app.use(cookieParser());
app.use("/api/auth", authRoutes);
app.use("/api", apiRoutes);
app.get("/api/health", (_req,res)=>res.json({status:"ok",timestamp:new Date().toISOString()}));
startJobs();
app.listen(PORT,()=>console.log(`🌾 KhetLink backend → http://localhost:${PORT}`));
export default app;
