import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { requireAuth, type AuthRequest } from "../middleware/auth.js";
const router=Router(); router.use(requireAuth);
const schema=z.object({productId:z.string(),quantity:z.number().positive(),unit:z.string().min(1),price:z.number().positive(),status:z.enum(["Active","Sold","Paused"]).default("Active")});
router.get("/",async(req:AuthRequest,res)=>{const listings=await prisma.listing.findMany({where:{status:"Active"},include:{product:{include:{category:true}},farmer:{include:{farmer:true}}},orderBy:{createdAt:"desc"}});res.json({listings});});
router.get("/mine",async(req:AuthRequest,res)=>res.json({listings:await prisma.listing.findMany({where:{farmerId:req.userId!},include:{product:true},orderBy:{createdAt:"desc"}})}));
router.post("/",async(req:AuthRequest,res)=>{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({error:"Invalid listing",details:p.error.flatten()});const role=await prisma.userRole.findUnique({where:{userId_role:{userId:req.userId!,role:"FARMER"}}});if(!role)return res.status(403).json({error:"Farmer role required"});res.status(201).json(await prisma.listing.create({data:{...p.data,farmerId:req.userId!}}));});
router.patch("/:id",async(req:AuthRequest,res)=>{const p=schema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({error:"Invalid listing"});const id=typeof req.params.id==="string"?req.params.id:null;if(!id)return res.status(400).json({error:"Invalid listing id"});const own=await prisma.listing.findFirst({where:{id,farmerId:req.userId!}});if(!own)return res.status(404).json({error:"Listing not found"});res.json(await prisma.listing.update({where:{id:own.id},data:p.data}));});
export default router;
