import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { requireAuth, type AuthRequest } from "../middleware/auth.js";
const router = Router(); router.use(requireAuth);
const schema = z.object({ email:z.string().email().optional(), firstName:z.string().min(1).optional(), lastName:z.string().min(1).optional(), phone:z.string().min(7).optional(), profileImage:z.string().optional(), location:z.string().optional(), latitude:z.number().nullable().optional(), longitude:z.number().nullable().optional(), language:z.string().optional(), company:z.string().optional(), farmName:z.string().optional(), farmArea:z.string().optional(), landAcres:z.number().nullable().optional(), experience:z.string().optional(), sellingArea:z.string().optional(), capacity:z.number().nonnegative().optional(), capabilities:z.string().optional(), produce:z.array(z.string()).optional() });
router.get("/me", async (req: AuthRequest,res)=>{ const user=await prisma.user.findUnique({where:{id:req.userId!},include:{roles:true,farmer:true,buyer:true,logistics:true}}); if(!user)return res.status(404).json({error:"User not found"}); const {password,...safe}=user; res.json({user:safe}); });
router.patch("/me", async(req:AuthRequest,res)=>{ const p=schema.safeParse(req.body); if(!p.success)return res.status(400).json({error:"Invalid profile data",details:p.error.flatten()}); const d=p.data; const user=await prisma.user.update({where:{id:req.userId!},data:{email:d.email,firstName:d.firstName,lastName:d.lastName,phone:d.phone,profileImage:d.profileImage,location:d.location,latitude:d.latitude,longitude:d.longitude,language:d.language}}); const roles=await prisma.userRole.findMany({where:{userId:req.userId!}}); if(roles.some(r=>r.role==="BUYER")) await prisma.buyerProfile.update({where:{userId:req.userId!},data:{company:d.company}}).catch(()=>{}); if(roles.some(r=>r.role==="FARMER")) await prisma.farmerProfile.update({where:{userId:req.userId!},data:{farmName:d.farmName,farmArea:d.farmArea,landAcres:d.landAcres,experience:d.experience,sellingArea:d.sellingArea,produce:d.produce}}).catch(()=>{}); if(roles.some(r=>r.role==="LOGISTICS")) await prisma.logisticsProfile.update({where:{userId:req.userId!},data:{capacity:d.capacity,capabilities:d.capabilities,availableCapacity:d.capacity}}).catch(()=>{}); res.json({user}); });
export default router;
