import { Router } from "express";
import crypto from "node:crypto";
import { prisma } from "../../lib/prisma.js";
const router=Router();
function twilioSignature(url:string,params:Record<string,string>){const data=url+Object.keys(params).sort().map(k=>k+params[k]).join("");return crypto.createHmac("sha1",process.env.TWILIO_AUTH_TOKEN??"").update(data).digest("base64")}
async function sendWhatsApp(to:string,body:string){const sid=process.env.TWILIO_ACCOUNT_SID,token=process.env.TWILIO_AUTH_TOKEN,from=process.env.TWILIO_WHATSAPP_FROM ?? process.env.TWILIO_WHATSAPP_NUMBER;if(!sid||!token||!from)return;const auth=Buffer.from(`${sid}:${token}`).toString("base64");const params=new URLSearchParams({From:from!.startsWith("whatsapp:")?from!:`whatsapp:${from!}`,To:to.startsWith("whatsapp:")?to:`whatsapp:${to}`,Body:body});await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:"POST",headers:{Authorization:`Basic ${auth}`,"Content-Type":"application/x-www-form-urlencoded"},body:params});}
export async function sendOrderWhatsApp(phone:string,body:string){return sendWhatsApp(phone,body)}
router.post("/webhook",async(req,res)=>{const signature=req.header("x-twilio-signature");const url=`${req.protocol}://${req.get("host")}${req.originalUrl}`;if(process.env.TWILIO_AUTH_TOKEN&&signature&&signature!==twilioSignature(url,req.body))return res.status(403).send("Invalid signature");const from=String(req.body?.From??"").replace(/^whatsapp:/,"");const text=String(req.body?.Body??"").trim().toUpperCase();const user=await prisma.user.findFirst({where:{phone:{contains:from.replace(/\D/g,"").slice(-10)}}});if(!user)return res.type("text/xml").send("<Response><Message>We could not match this WhatsApp number to a KhetLink account.</Message></Response>");const roles=await prisma.userRole.findMany({where:{userId:user.id}});const farmer=roles.some(r=>r.role==="FARMER");if(text==="HELP"||text==="MENU"){const body=farmer?"KhetLink Farmer\n1. Add Listing\n2. Update Listing\n3. Check Orders\n4. Check Earnings\n5. Shipment\n6. Notifications\n7. Profile\n8. Analytics\n9. Help":"KhetLink\nReply DETAILS for your latest relevant order information.";return res.type("text/xml").send(`<Response><Message>${body}</Message></Response>`)}if(text==="DETAILS"){const order=await prisma.order.findFirst({where:{OR:[{buyerId:user.id},{sellerId:user.id}],paymentStatus:"PAID"},include:{items:{include:{product:true}},shipment:true},orderBy:{createdAt:"desc"}});if(!order)return res.type("text/xml").send("<Response><Message>No paid order is currently associated with your account.</Message></Response>");const items=order.items.map(i=>`${i.product.name}: ${i.quantity} ${i.unit}`).join("\n");const body=`KhetLink — Order Update\nOrder: ${order.id}\n${items}\nStatus: ${order.status}\nPayment: ${order.paymentStatus}\nShipment: ${order.shipment?.status??"Confirmed"}\nETA: ${order.shipment?.etaMinutes??"—"} minutes`;return res.type("text/xml").send(`<Response><Message>${body}</Message></Response>`)}return res.type("text/xml").send("<Response><Message>Reply MENU for KhetLink actions or DETAILS for your latest order.</Message></Response>")});
export default router;
