"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Truck, MapPin, Bell, UserCircle, Check, X } from "lucide-react";

type Offer={id:string;order:{id:string;items:{quantity:number;unit:string;product:{name:string}}[];shipment?:{pickupLocation?:string;deliveryLocation?:string;distanceKm?:number;etaMinutes?:number}}};
export default function LogisticsPage(){
 const [offers,setOffers]=useState<Offer[]>([]); const [profile,setProfile]=useState<any>(null); const [error,setError]=useState("");
 const load=async()=>{try{const [o,p]=await Promise.all([fetch('/api/logistics/offers',{credentials:'include'}),fetch('/api/profile/me',{credentials:'include'})]); if(!o.ok){setError('Activate the Logistics role first.');return;} setOffers((await o.json()).offers??[]); if(p.ok)setProfile((await p.json()).user)}catch{setError('Unable to load logistics data.')}};
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
 const accept=async(id:string)=>{const r=await fetch(`/api/logistics/offers/${id}/accept`,{method:'POST',credentials:'include'});if(!r.ok){setError((await r.json()).error??'Unable to accept offer');return;}load()}; const decline=async(id:string)=>{const r=await fetch(`/api/logistics/offers/${id}/decline`,{method:'POST',credentials:'include'});if(r.ok)load()};
 return <main style={{minHeight:'100vh',background:'#f5f7f1',padding:32,fontFamily:'Arial,sans-serif'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:28}}><Link href="/" style={{fontWeight:800,fontSize:24,color:'#173b24',textDecoration:'none'}}>KhetLink</Link><div style={{display:'flex',gap:16,alignItems:'center'}}><span>{profile?.firstName} {profile?.lastName}</span><UserCircle/></div></header><section style={{maxWidth:1100,margin:'auto'}}><div style={{background:'#173b24',color:'white',borderRadius:22,padding:28,marginBottom:22}}><div style={{display:'flex',gap:14,alignItems:'center'}}><Truck/><div><div style={{opacity:.75,fontSize:13}}>LOGISTICS INTERFACE</div><h1 style={{margin:'4px 0'}}>Transport Offers</h1><p style={{margin:0,opacity:.85}}>Paid KhetLink orders available for delivery.</p></div></div></div>{error&&<div style={{padding:14,background:'#fee2e2',borderRadius:12,marginBottom:16}}>{error}</div>}<div style={{display:'grid',gap:16}}>{offers.length===0?<div style={{background:'white',padding:28,borderRadius:18}}>No paid transport offers right now.</div>:offers.map(o=><article key={o.id} style={{background:'white',padding:22,borderRadius:18,boxShadow:'0 4px 20px rgba(0,0,0,.05)'}}><div style={{display:'flex',justifyContent:'space-between',gap:20}}><div><strong>Order {o.order.id}</strong>{o.order.items.map((i,n)=><div key={n} style={{marginTop:8}}>{i.product.name} — {i.quantity} {i.unit}</div>)}<p><MapPin size={15}/> {o.order.shipment?.pickupLocation??'Pickup'} → {o.order.shipment?.deliveryLocation??'Delivery'}</p><small>{o.order.shipment?.distanceKm??'—'} km · ETA {o.order.shipment?.etaMinutes??'—'} min</small></div><div style={{display:'flex',gap:8,alignItems:'start'}}><button onClick={()=>accept(o.id)} style={{border:0,borderRadius:10,padding:'10px 16px',background:'#1d6b3a',color:'white'}}><Check size={16}/> Accept</button><button style={{border:0,borderRadius:10,padding:'10px 16px',background:'#eee'}}><X size={16}/> Decline</button></div></div></article>)}</div><nav style={{display:'flex',gap:18,marginTop:28}}><Link href="/logistics" >Dashboard</Link><Link href="/logistics/profile">Profile</Link></nav></section></main>;
}
